spring.profiles.active: dev

zuul:
  routes:
    users:
      path: /api/users/**
      url: http://localhost:8081
      stripPrefix: false
    namespaces:
      path: /api/namespaces/**
      url: http://localhost:8081
      stripPrefix: false
    apps:
      path: /api/apps/**
      url: http://localhost:8081
      stripPrefix: false
    environments:
      path: /api/environments/**
      url: http://localhost:8081
      stripPrefix: false
    blueprints:
      path: /api/blueprints/**
      url: http://localhost:8081
      stripPrefix: false
    runs:
      path: /api/runs/**
      url: http://localhost:8082
      stripPrefix: false

testament.gateway.security.jwt:
  uri: /auth/login
  header: Authorization
  prefix: "Bearer "
  expiration: 86400

ribbon.eureka.enabled: false

---

spring.profiles: dev
testament.gateway.security.jwt.secret: some_secret
#testament.gateway.security.jwt.secret: ${TESTAMENT_JWT_SECRET}
server.port: 8080
